# address endpoint tests

## I insert a dummy record

POST https://localhost:5001/api/addresses HTTP/1.1
Content-Type: application/json
Content-Length: 

{
  "Name": "",
  "Civic": "",
  "City": "",
  "District": "",
  "Postcode": "",
  "Country": ""
}

## I insert another one

POST https://localhost:5001/api/addresses HTTP/1.1
Content-Type: application/json
Content-Length: 

{
  "Name": "",
  "Civic": "",
  "City": "",
  "District": "",
  "Postcode": "",
  "Country": ""
}

## I insert another one

POST https://localhost:5001/api/addresses HTTP/1.1
  Content-Type: application/json
Content-Length: 

{
  "Name": "",
  "Civic": "",
  "City": "",
  "District": "",
  "Postcode": "",
  "Country": ""
}

## read

GET https://localhost:5001/api/addresses/2 HTTP/1.1

## read all

GET https://localhost:5001/api/addresses HTTP/1.1

## update a dummy data with id 2

PUT https://localhost:5001/api/addresses/2 HTTP/1.1
Content-Type: application/json
Content-Length: 

{
  "id": 2,
  "Name": "",
  "Civic": "",
  "City": "",
  "District": "",
  "Postcode": "",
  "Country": "",
  "carriers": [],
  "customers": [],
  "employees": [],
  "suppliers": []
}

## partial update a dummy data with id 2

PATCH https://localhost:5001/api/addresses/2 HTTP/1.1
Content-Type: application/json
Content-Length: 

{
  "id": 2,
  "Name": ""
}

## delete an identified data entry

DELETE https://localhost:5001/api/addresses/1 HTTP/1.1
