# supplier endpoint tests

## For example, values ​​can be generated pseudo-randomly with the following shell command:
### cat /dev/urandom | tr -dc 'A-Z' | fold -w 16 | head -n 1

### I insert a dummy record

POST https://localhost:5001/api/suppliers HTTP/1.1
Content-Type: application/json
Content-Length: 131

{
  "Name": "YUFMXPAGQJCWBAZD",
  "FoundationDate": "2015-11-01T00:00:00",
  "Description": "YJCLVRLJBANKJFSUFFMCGFRRSFYSGKVW",
  "Belonging": "C"
}

### I insert another one

POST https://localhost:5001/api/suppliers HTTP/1.1
Content-Type: application/json
Content-Length: 131

{
  "Name": "RUKMIRZCTXJNCXMC",
  "FoundationDate": "2016-10-10T00:00:00",
  "Description": "SQJBWCKRAZYKGKIWHSLKWMXFISQRNGPM",
  "Belonging": "B"
}

### I insert another one

POST https://localhost:5001/api/suppliers HTTP/1.1
Content-Type: application/json
Content-Length: 131

{
  "Name": "UXOMHRKGBCQICQFO",
  "FoundationDate": "2017-03-29T00:00:00",
  "Description": "MLYNQPMXMXLLFVUGHAKMKEYNTVUWQHJS",
  "Belonging": "A"
}

### read

GET https://localhost:5001/api/suppliers/2 HTTP/1.1

### read all

GET https://localhost:5001/api/suppliers HTTP/1.1

### update a dummy data with id 2

PUT https://localhost:5001/api/suppliers/2 HTTP/1.1
Content-Type: application/json
Content-Length: 271

{
  "id": 2,
  "name": "RUKMIRZCTXJNCXMC",
  "foundationDate": "2016-10-09T00:00:00",
  "description": "ZJDBXESCQRUFTATPXRKHFZPNGWGKKGXG",
  "picture": null,
  "belonging": "B",
  "contact": null,
  "loc": null,
  "ref": null,
  "contactNavigation": null,
  "locNavigation": null,
  "products": [],
  "refNavigation": null
}

### partial update a dummy data with id 2

PATCH https://localhost:5001/api/suppliers/2 HTTP/1.1
Content-Type: application/json
Content-Length: 122

{
  "id": 2,
  "name": "RUKMIRZCTXJNCXMC",
  "foundationDate": "2016-10-09T00:00:00",
  "description": "ATXMFKKJETJDAQAHXRBTBKRROAXHKDTT"
}

### delete an identified data entry

DELETE https://localhost:5001/api/suppliers/1 HTTP/1.1
