# supplier endpoint tests

### inserting dummy data

POST https://localhost:5001/api/suppliers HTTP/1.1
Content-Type: application/json
Content-Length: 

{
  "Name": "",
  "FoundationDate": "",
  "Description": "",
  "Picture": ""
}

### inserting dummy data

POST https://localhost:5001/api/suppliers HTTP/1.1
Content-Type: application/json
Content-Length: 

{
  "Name": "",
  "FoundationDate": "",
  "Description": "",
  "Picture": ""
}

### inserting dummy data

POST https://localhost:5001/api/suppliers HTTP/1.1
Content-Type: application/json
Content-Length: 

{
  "Name": "",
  "FoundationDate": "",
  "Description": "",
  "Picture": ""
}

### read

GET https://localhost:5001/api/suppliers/2 HTTP/1.1

### read all

GET https://localhost:5001/api/suppliers HTTP/1.1

### update a dummy data with id 2

PUT https://localhost:5001/api/suppliers/2 HTTP/1.1
Content-Type: application/json
Content-Length: 

{
  "id": ""
}

### partial update a dummy data with id 2

PATCH https://localhost:5001/api/suppliers/2 HTTP/1.1
Content-Type: application/json
Content-Length: 

{
  "id": ""
}

### delete an identified data entry

DELETE https://localhost:5001/api/suppliers/1 HTTP/1.1
