# address endpoint tests

## For example, values ​​can be generated pseudo-randomly with the following shell command:
### cat /dev/urandom | tr -dc 'A-Z' | fold -w 16 | head -n 1

### record number 1

POST https://localhost:5001/api/addresses HTTP/1.1
Content-Type: application/json
Content-Length: 129

{
  "Name": "MNTRHRQPMVQDOMSI",
  "Civic": "297",
  "City": "EWRXAJMFID",
  "District": "ODYTNIVNUKQJ",
  "Postcode": "3876629",
  "Country": "QSSHVCVZ"
}

### record number 2

POST https://localhost:5001/api/addresses HTTP/1.1
Content-Type: application/json
Content-Length: 129

{
  "Name": "CHQBFKGGYDGRFSKP",
  "Civic": "589",
  "City": "RERXDNJODQ",
  "District": "CHUYEHGHUDOE",
  "Postcode": "8813283",
  "Country": "YUSHHXXS"
}

### record number 3

POST https://localhost:5001/api/addresses HTTP/1.1
  Content-Type: application/json
Content-Length: 129

{
  "Name": "KQEPPOVUWAJNCIKV",
  "Civic": "914",
  "City": "GWNLKXHKAX",
  "District": "LJAFGJKXDICP",
  "Postcode": "9515428",
  "Country": "UDQNEIEC"
}

### record number 4

POST https://localhost:5001/api/addresses HTTP/1.1
Content-Type: application/json
Content-Length: 129

{
  "Name": "KYJOFLFGBSMNWOUS",
  "Civic": "451",
  "City": "EWRXAJMFID",
  "District": "ODYTNIVNUKQJ",
  "Postcode": "3876629",
  "Country": "QSSHVCVZ"
}

### record number 5

POST https://localhost:5001/api/addresses HTTP/1.1
Content-Type: application/json
Content-Length: 129

{
  "Name": "NWQWCSQKUBBWBJAZ",
  "Civic": "766",
  "City": "RERXDNJODQ",
  "District": "CHUYEHGHUDOE",
  "Postcode": "8813283",
  "Country": "YUSHHXXS"
}

### record number 6

POST https://localhost:5001/api/addresses HTTP/1.1
  Content-Type: application/json
Content-Length: 129

{
  "Name": "DAXSGIRIGSEITAYB",
  "Civic": "884",
  "City": "GWNLKXHKAX",
  "District": "LJAFGJKXDICP",
  "Postcode": "9515428",
  "Country": "UDQNEIEC"
}

### record number 7

POST https://localhost:5001/api/addresses HTTP/1.1
Content-Type: application/json
Content-Length: 129

{
  "Name": "CJLELJLDZGVFRHKV",
  "Civic": "437",
  "City": "EWRXAJMFID",
  "District": "ODYTNIVNUKQJ",
  "Postcode": "3876629",
  "Country": "QSSHVCVZ"
}

### record number 8

POST https://localhost:5001/api/addresses HTTP/1.1
Content-Type: application/json
Content-Length: 129

{
  "Name": "ZBFLFCZDCEWBIXOV",
  "Civic": "732",
  "City": "RERXDNJODQ",
  "District": "CHUYEHGHUDOE",
  "Postcode": "8813283",
  "Country": "YUSHHXXS"
}

### record number 9

POST https://localhost:5001/api/addresses HTTP/1.1
  Content-Type: application/json
Content-Length: 129

{
  "Name": "KQEPPOVUWAJNCIKV",
  "Civic": "914",
  "City": "GWNLKXHKAX",
  "District": "LJAFGJKXDICP",
  "Postcode": "9515428",
  "Country": "UDQNEIEC"
}

### read

GET https://localhost:5001/api/addresses/2 HTTP/1.1

### read all

GET https://localhost:5001/api/addresses HTTP/1.1

### update a dummy data with id 2

PUT https://localhost:5001/api/addresses/2 HTTP/1.1
Content-Type: application/json
Content-Length: 194

{
  "id": 2,
  "name": "CHQBFKGGYDGRFSKP",
  "civic": "34",
  "city": "RERXDNJODQ",
  "district": "CHUYEHGHUDOE",
  "postcode": "8813283",
  "country": "YUSHHXXS",
  "carriers": [],
  "customers": [],
  "employees": [],
  "suppliers": []
}

### partial update a dummy data with id 2

PATCH https://localhost:5001/api/addresses/2 HTTP/1.1
Content-Type: application/json
Content-Length: 21

{
  "id": 2,
  "civic": "61"
}

### delete an identified data entry

DELETE https://localhost:5001/api/addresses/1 HTTP/1.1
