# product endpoint tests

## For example, values ​​can be generated pseudo-randomly with the following shell command:
### cat /dev/urandom | tr -dc 'A-Z' | fold -w 16 | head -n 1

### record number 1

POST https://localhost:5001/api/products HTTP/1.1
Content-Type: application/json
Content-Length: 99

{
  "Name": "VQXALVGYMYKCPANW",
  "Description": "GMUWTWHIFBCRTWYJIBKYGECCTLJPDBSB",
  "QuantityPerUnit": "12"
}

### record number 2

POST https://localhost:5001/api/products HTTP/1.1
Content-Type: application/json
Content-Length: 99

{
  "Name": "LRRYQQDRUWESISBE",
  "Description": "LHMHDWCGSCDPMOIDNPCXCNMMFVKWJADO",
  "QuantityPerUnit": "18"
}

### record number 3

POST https://localhost:5001/api/products HTTP/1.1
Content-Type: application/json
Content-Length: 99

{
  "Name": "QJKUTTKNONZRNHCK",
  "Description": "LVWODVRJUVZOXXVWIDHHKAXOLPUTPNSI",
  "QuantityPerUnit": "24"
}

### read

GET https://localhost:5001/api/products/2 HTTP/1.1

### read all

GET https://localhost:5001/api/products HTTP/1.1

### update a dummy data with id 2

PUT https://localhost:5001/api/products/2 HTTP/1.1
Content-Type: application/json
Content-Length: 289

{
  "id": 2,
  "name": "LRRYQQDRUWESISBE",
  "description": "GOEFJYISFXRFUVUROMZIYUAYBBOAATTT",
  "picture": null,
  "categoryId": null,
  "supplierId": null,
  "quantityPerUnit": "18",
  "unitPrice": 0,
  "unitsInStock": 0,
  "unitsOnOrder": 0,
  "reorderLevel": 0,
  "discontinued": false,
  "category": null,
  "invoices": [],
  "supplier": null
}

### partial update a dummy data with id 2

PATCH https://localhost:5001/api/products/2 HTTP/1.1
Content-Type: application/json
Content-Length: 83

{
  "id": 2,
  "name": "LRRYQQDRUWESISBE",
  "description": "CMNWACAMJVZRBUOHCLGNTRIEUJFEKMSZ"
}

### delete an identified data entry

DELETE https://localhost:5001/api/products/1 HTTP/1.1
