# address endpoint tests

### create a new fictitious data entry

POST https://localhost:5001/api/addresses HTTP/1.1
Content-Type: application/json
Content-Length: 232

{
  "StreetOrSquare": "Some Street One",
  "Civic": "151/B",
  "City": "SomeOneCity",
  "District": "SomeOneDistrict",
  "Postcode": "010101",
  "Country": "SomeOneCountry",
  "Email": "some.one@example.local",
  "Phone": "039035801010101",
  "Fax": "039035801010102"
}

### read all

GET https://localhost:5001/api/addresses HTTP/1.1
