# form endpoint tests

### inserting dummy data

POST https://localhost:5001/api/forms HTTP/1.1
Content-Type: application/json
Content-Length: 

{
  "Description": "",
  "FormDate": "",
  "RequiredDate": "",
  "PromisedDate": "",
  "ShippingCost": ""
}

### inserting dummy data

POST https://localhost:5001/api/forms HTTP/1.1
Content-Type: application/json
Content-Length: 

{
  "Description": "",
  "FormDate": "",
  "RequiredDate": "",
  "PromisedDate": "",
  "ShippingCost": ""
}

### inserting dummy data

POST https://localhost:5001/api/forms HTTP/1.1
Content-Type: application/json
Content-Length: 

{
  "Description": "",
  "FormDate": "",
  "RequiredDate": "",
  "PromisedDate": "",
  "ShippingCost": ""
}

### read

GET https://localhost:5001/api/forms/2 HTTP/1.1

### read all

GET https://localhost:5001/api/forms HTTP/1.1

### update a dummy data with id 2

PUT https://localhost:5001/api/forms/2 HTTP/1.1
Content-Type: application/json
Content-Length: 

{
  "id": ""
}

### partial update a dummy data with id 2

PATCH https://localhost:5001/api/forms/2 HTTP/1.1
Content-Type: application/json
Content-Length: 

{
  "id": ""
}

### delete an identified data entry

DELETE https://localhost:5001/api/forms/1 HTTP/1.1
