# credential endpoint tests

## For example, values ​​can be generated pseudo-randomly with the following shell command:
### cat /dev/urandom | tr -dc 'A-Z' | fold -w 16 | head -n 1

### record number 1

POST https://localhost:5001/api/credentials HTTP/1.1
Content-Type: application/json
Content-Length: 79

{
  "Email": "2702t3f.s8bhne8@example.local",
  "Phone": "873395959",
  "Fax": "873395958"
}

### record number 2

POST https://localhost:5001/api/credentials HTTP/1.1
Content-Type: application/json
Content-Length: 79

{
  "Email": "xgk3yb3.tumkcl4@example.local",
  "Phone": "161477718",
  "Fax": "161477717"
}

### record number 3

POST https://localhost:5001/api/credentials HTTP/1.1
Content-Type: application/json
Content-Length: 79

{
  "Email": "o7rb02e.iqtfzrg@example.local",
  "Phone": "959393342",
  "Fax": "959393341"
}

### read

GET https://localhost:5001/api/credentials/2 HTTP/1.1

### read all

GET https://localhost:5001/api/credentials HTTP/1.1

### update a dummy data with id 2

PUT https://localhost:5001/api/credentials/2 HTTP/1.1
Content-Type: application/json
Content-Length: 145

{
  "id": 2,
  "email": "xgk3yb3.tumkcl4@example.local",
  "phone": "161477718",
  "fax": "161477717",
  "carriers": [],
  "customers": [],
  "employees": [],
  "suppliers": []
}

### partial update a dummy data with id 2

PATCH https://localhost:5001/api/credentials/2 HTTP/1.1
Content-Type: application/json
Content-Length: 26

{
  "id": 2,
  "fax": "161477719"
}

### delete an identified data entry

DELETE https://localhost:5001/api/credentials/1 HTTP/1.1
